import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

const _revision = '173b9b26e8fcbcbe64e1ecbf073a21a96b95c6b1';
const _metadataRoot =
    'https://raw.githubusercontent.com/googlefonts/emoji-metadata/$_revision';
const _metadataUrl = '$_metadataRoot/emoji_17_0_ordering.json';
const _artworkRoot = 'https://fonts.gstatic.com/s/e/notoemoji/latest';

// This importer is deliberately separate from the runtime library. It writes
// only package-owned Noto resources, records their hashes, and never runs when
// an application launches.
Future<void> main(List<String> arguments) async {
  if (arguments.isNotEmpty) {
    throw ArgumentError('This importer does not accept arguments');
  }
  final root = Platform.script.resolve('../');
  final client = HttpClient()..maxConnectionsPerHost = 6;
  try {
    final metadataBytes = await _download(client, Uri.parse(_metadataUrl));
    final groups = jsonDecode(utf8.decode(metadataBytes)) as List<dynamic>;
    final entries = <String, _Entry>{};
    for (final group in groups.cast<Map<String, dynamic>>()) {
      for (final emoji
          in (group['emoji'] as List).cast<Map<String, dynamic>>()) {
        if (emoji['animated'] != true) continue;
        final shortcodes = (emoji['shortcodes'] as List).cast<String>();
        final alternatives = <List<int>>[
          (emoji['base'] as List).cast<int>(),
          for (final value in emoji['alternates'] as List)
            (value as List).cast<int>(),
        ];
        for (final points in alternatives) {
          final id = points
              .map((p) => p.toRadixString(16).padLeft(4, '0'))
              .join('_');
          final entry = entries.putIfAbsent(
            id,
            () => _Entry(
              id: id,
              unicode: String.fromCharCodes(points),
              name: _name(shortcodes.first, points),
            ),
          );
          entry.categories.add(group['group'] as String);
          entry.keywords.addAll([
            ...shortcodes.map(
              (s) => s.replaceAll(':', '').replaceAll('-', ' '),
            ),
            ...(emoji['emoticons'] as List).cast<String>(),
          ]);
        }
      }
    }
    final ordered = entries.values.toList();
    final existing = File.fromUri(root.resolve('assets/noto/manifest.json'));
    final oldFiles = <String, Map<String, dynamic>>{};
    if (await existing.exists()) {
      final old =
          jsonDecode(await existing.readAsString()) as Map<String, dynamic>;
      for (final entry
          in (old['entries'] as List).cast<Map<String, dynamic>>()) {
        if (entry['lottie'] case final Map<String, dynamic> file) {
          oldFiles[file['path'] as String] = file;
        }
      }
    }
    var cursor = 0;
    var completed = 0;
    await Future.wait([
      for (var worker = 0; worker < 6; worker++)
        () async {
          while (cursor < ordered.length) {
            final entry = ordered[cursor++];
            entry.lottie = await _asset(
              client,
              root,
              entry.id,
              'lottie.json',
              'assets/noto/lottie/${entry.id}.json',
              oldFiles,
            );
            completed++;
            if (completed % 50 == 0 || completed == ordered.length) {
              stdout.writeln('Noto assets: $completed/${ordered.length}');
            }
          }
        }(),
    ]);
    final artworkIdentity = jsonEncode([
      for (final entry in ordered) [entry.id, entry.lottie!['sha256']],
    ]);
    final version =
        'noto-17.0-${sha256.convert(utf8.encode(artworkIdentity)).toString().substring(0, 12)}';
    final manifest = <String, Object?>{
      'version': version,
      'metadataSource': _metadataUrl,
      'metadataSha256': sha256.convert(metadataBytes).toString(),
      'artworkSource': _artworkRoot,
      'artworkLicense': 'CC-BY-4.0',
      'metadataLicense': 'Apache-2.0',
      'entries': [
        for (final entry in ordered)
          {
            'id': entry.id,
            'unicode': entry.unicode,
            'name': entry.name,
            'categories': entry.categories.toList(),
            'keywords': entry.keywords.toList(),
            'lottie': entry.lottie,
          },
      ],
    };
    await _write(
      root,
      'assets/noto/manifest.json',
      utf8.encode('${const JsonEncoder.withIndent('  ').convert(manifest)}\n'),
    );
    await _write(
      root,
      'licenses/Apache-2.0.txt',
      await _download(client, Uri.parse('$_metadataRoot/LICENSE')),
    );
    final source = StringBuffer(
      '''// Generated by tool/import_noto_assets.dart. Do not edit by hand.
// Metadata: Google emoji-metadata, Apache-2.0; see THIRD_PARTY_NOTICES.
// Source revision: $_revision (Emoji 17.0).

const notoCatalogVersion = '$version';
const notoEmojiEntries = <({String id, String unicode, String name, List<String> categories, List<String> keywords})>[
''',
    );
    for (final entry in ordered) {
      source.writeln(
        '  (id: ${_literal(entry.id)}, unicode: ${_literal(entry.unicode)}, name: ${_literal(entry.name)}, categories: ${_literal(entry.categories.toList())}, keywords: ${_literal(entry.keywords.toList())}),',
      );
    }
    source.writeln('];');
    await _write(
      root,
      'lib/src/catalog/noto_emoji_data.g.dart',
      utf8.encode(source.toString()),
    );
    final jsonBytes = ordered.fold<int>(
      0,
      (sum, entry) => sum + (entry.lottie!['bytes'] as int),
    );
    stdout.writeln(
      'Imported ${ordered.length} variants. JSON: $jsonBytes bytes.',
    );
  } finally {
    client.close(force: true);
  }
}

String _literal(Object value) => jsonEncode(value).replaceAll(r'$', r'\$');

String _name(String shortcode, List<int> points) {
  final base = shortcode.replaceAll(':', '').replaceAll('-', ' ');
  const tones = <int, String>{
    0x1f3fb: 'light skin tone',
    0x1f3fc: 'medium light skin tone',
    0x1f3fd: 'medium skin tone',
    0x1f3fe: 'medium dark skin tone',
    0x1f3ff: 'dark skin tone',
  };
  final modifiers = points
      .where(tones.containsKey)
      .map((p) => tones[p]!)
      .toList();
  return modifiers.isEmpty ? base : '$base: ${modifiers.join(', ')}';
}

Future<Map<String, dynamic>> _asset(
  HttpClient client,
  Uri root,
  String id,
  String remoteName,
  String path,
  Map<String, Map<String, dynamic>> existing,
) async {
  final file = File.fromUri(root.resolve(path));
  Uint8List? bytes;
  if (await file.exists()) {
    final local = await file.readAsBytes();
    if (sha256.convert(local).toString() == existing[path]?['sha256']) {
      bytes = local;
    }
  }
  bytes ??= await _download(client, Uri.parse('$_artworkRoot/$id/$remoteName'));
  final json = jsonDecode(utf8.decode(bytes)) as Map<String, dynamic>;
  if (json['layers'] is! List || json['w'] is! num || json['h'] is! num) {
    throw FormatException('Not a Lottie composition: $id');
  }
  if (!await file.exists() ||
      existing[path]?['sha256'] != sha256.convert(bytes).toString()) {
    await _write(root, path, bytes);
  }
  return {
    'path': path,
    'url': '$_artworkRoot/$id/$remoteName',
    'bytes': bytes.length,
    'sha256': sha256.convert(bytes).toString(),
  };
}

Future<Uint8List> _download(HttpClient client, Uri uri) async {
  for (var attempt = 0; ; attempt++) {
    try {
      return await (() async {
        final request = await client.getUrl(uri);
        request.followRedirects = false;
        final response = await request.close();
        if (response.statusCode != HttpStatus.ok) {
          await response.drain<void>();
          throw HttpException('HTTP ${response.statusCode}', uri: uri);
        }
        final bytes = BytesBuilder(copy: false);
        await for (final chunk in response) {
          bytes.add(chunk);
          if (bytes.length > 16 * 1024 * 1024) {
            throw FormatException('Asset exceeds the import limit: $uri');
          }
        }
        return bytes.takeBytes();
      })().timeout(const Duration(seconds: 30));
    } on HttpException catch (error) {
      if (!error.message.contains('HTTP 5') || attempt >= 2) rethrow;
    } on IOException {
      if (attempt >= 2) rethrow;
    } on TimeoutException {
      if (attempt >= 2) rethrow;
    }
    await Future<void>.delayed(Duration(milliseconds: 300 * (attempt + 1)));
  }
}

Future<void> _write(Uri root, String path, List<int> bytes) async {
  final file = File.fromUri(root.resolve(path));
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes, flush: true);
}

final class _Entry {
  _Entry({required this.id, required this.unicode, required this.name});
  final String id;
  final String unicode;
  final String name;
  final Set<String> categories = {};
  final Set<String> keywords = {};
  Map<String, dynamic>? lottie;
}
