import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_animated_media/flutter_animated_media.dart';

/// Original MIT-licensed fixtures: a vector pulse and a two-color GIF.
final demoCatalog = LocalMediaCatalog([
  MediaItem(
    id: 'pulse',
    provider: 'example',
    version: '1',
    name: 'Pulse',
    kind: MediaKind.sticker,
    format: MediaFormat.lottie,
    categories: ['Shapes'],
    keywords: ['circle', 'pulse'],
    source: MediaSource.memory(
      'pulse-v1',
      Uint8List.fromList(utf8.encode(pulseJson)),
    ),
    attribution: _attribution,
  ),
  MediaItem(
    id: 'color',
    provider: 'example',
    version: '1',
    name: 'Color tile',
    kind: MediaKind.sticker,
    format: MediaFormat.gif,
    categories: ['Shapes'],
    keywords: ['color', 'tile'],
    source: MediaSource.memory('color-v1', colorGif),
    attribution: _attribution,
  ),
]);

final _attribution = MediaAttribution(
  author: 'flutter_animated_media contributors',
  source: Uri.parse('https://example.org/original-fixtures'),
  license: 'MIT',
  licenseUrl: Uri.parse('https://opensource.org/license/mit'),
);

// Hand-authored GIF89a: 1x1, two frames, red/blue palette, 200 ms per frame.
final colorGif = Uint8List.fromList([
  71,
  73,
  70,
  56,
  57,
  97,
  1,
  0,
  1,
  0,
  128,
  0,
  0,
  255,
  0,
  0,
  0,
  0,
  255,
  33,
  249,
  4,
  0,
  20,
  0,
  0,
  0,
  44,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  2,
  2,
  68,
  1,
  0,
  33,
  249,
  4,
  0,
  20,
  0,
  0,
  0,
  44,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  2,
  2,
  76,
  1,
  0,
  59,
]);

const pulseJson = '''{
  "v":"5.7.4","fr":30,"ip":0,"op":30,"w":64,"h":64,
  "nm":"Original pulse fixture","ddd":0,"assets":[],
  "markers":[{"tm":15,"cm":"rest","dr":1}],
  "layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Circle","sr":1,
    "ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},
      "p":{"a":0,"k":[32,32,0]},"a":{"a":0,"k":[0,0,0]},
      "s":{"a":1,"k":[
        {"t":0,"s":[65,65,100],"e":[100,100,100],"o":{"x":0.33,"y":0},"i":{"x":0.67,"y":1}},
        {"t":15,"s":[100,100,100],"e":[65,65,100],"o":{"x":0.33,"y":0},"i":{"x":0.67,"y":1}},
        {"t":30,"s":[65,65,100]}]}},
    "shapes":[{"ty":"el","p":{"a":0,"k":[0,0]},"s":{"a":0,"k":[48,48]},"nm":"Ellipse"},
      {"ty":"fl","c":{"a":0,"k":[0.25,0.35,0.9,1]},"o":{"a":0,"k":100},"r":1,"nm":"Fill"}],
    "ip":0,"op":30,"st":0,"bm":0}]
}''';
